/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'home-content': HomeContent;
    projects: Project;
    'projects-content': ProjectsContent;
    media: Media;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'projects-content': ProjectsContentSelect<false> | ProjectsContentSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  title?: string | null;
  heroCreativeLabel: string;
  heroDescription: string;
  aboutHeroImage: number | Media;
  aboutHeroText: string;
  aboutDeveloperDescription: string;
  aboutStudentDescription: string;
  aboutSelfDevDescription: string;
  aboutCreativeDescription: string;
  aboutDeveloperImage: number | Media;
  aboutStudentImage: number | Media;
  aboutCreativeImage: number | Media;
  aboutSmallImage: number | Media;
  techStacks?:
    | {
        name: string;
        theme: 'purple' | 'green' | 'red' | 'blue' | 'orange';
        items?:
          | {
              label: string;
              icon: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  educationQuote: string;
  educationQuoteAuthor: string;
  educationBodyText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  extracurricularActivities?:
    | {
        activityName: string;
        id?: string | null;
      }[]
    | null;
  educationItems?:
    | {
        title: string;
        completionYears: string;
        focus: string;
        providerLogo: number | Media;
        primarySubject: string;
        secondarySubject: string;
        tertiarySubject: string;
        mission: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  inspirations?:
    | {
        title: string;
        description: string;
        image: number | Media;
        link: string;
        id?: string | null;
      }[]
    | null;
  socialCards?:
    | {
        platform: 'github' | 'linkedin' | 'instagram' | 'spotify';
        title: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  contactDescription: string;
  location: string;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  projectBehaviour: {
    /**
     * e.g. 'ai-databases'
     */
    slug: string;
    isFeatured?: boolean | null;
    isHighlighted?: boolean | null;
  };
  projectDetails?: {
    featuredImage?: (number | null) | Media;
    subtitle?: string | null;
    description?: string | null;
  };
  externalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  technologies?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  projectArticle?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-content".
 */
export interface ProjectsContent {
  id: number;
  title: string;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'home-content';
        value: number | HomeContent;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'projects-content';
        value: number | ProjectsContent;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  title?: T;
  heroCreativeLabel?: T;
  heroDescription?: T;
  aboutHeroImage?: T;
  aboutHeroText?: T;
  aboutDeveloperDescription?: T;
  aboutStudentDescription?: T;
  aboutSelfDevDescription?: T;
  aboutCreativeDescription?: T;
  aboutDeveloperImage?: T;
  aboutStudentImage?: T;
  aboutCreativeImage?: T;
  aboutSmallImage?: T;
  techStacks?:
    | T
    | {
        name?: T;
        theme?: T;
        items?:
          | T
          | {
              label?: T;
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  educationQuote?: T;
  educationQuoteAuthor?: T;
  educationBodyText?: T;
  extracurricularActivities?:
    | T
    | {
        activityName?: T;
        id?: T;
      };
  educationItems?:
    | T
    | {
        title?: T;
        completionYears?: T;
        focus?: T;
        providerLogo?: T;
        primarySubject?: T;
        secondarySubject?: T;
        tertiarySubject?: T;
        mission?: T;
        id?: T;
      };
  inspirations?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  socialCards?:
    | T
    | {
        platform?: T;
        title?: T;
        link?: T;
        id?: T;
      };
  contactDescription?: T;
  location?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  projectBehaviour?:
    | T
    | {
        slug?: T;
        isFeatured?: T;
        isHighlighted?: T;
      };
  projectDetails?:
    | T
    | {
        featuredImage?: T;
        subtitle?: T;
        description?: T;
      };
  externalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        label?: T;
        id?: T;
      };
  projectArticle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-content_select".
 */
export interface ProjectsContentSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnBlock".
 */
export interface TwoColumnBlock {
  leftColumn?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text-block';
          }
        | {
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-block';
          }
        | {
            quote: string;
            author?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote-block';
          }
        | {
            type?: ('unordered' | 'ordered') | null;
            items: {
              item: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'list-block';
          }
        | {
            language?: ('typescript' | 'javascript' | 'html-css' | 'json') | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'code-block';
          }
      )[]
    | null;
  rightColumn?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text-block';
          }
        | {
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-block';
          }
        | {
            quote: string;
            author?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote-block';
          }
        | {
            type?: ('unordered' | 'ordered') | null;
            items: {
              item: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'list-block';
          }
        | {
            language?: ('typescript' | 'javascript' | 'html-css' | 'json') | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'code-block';
          }
      )[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'two-column';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeColumnBlock".
 */
export interface ThreeColumnBlock {
  leftColumn?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text-block';
          }
        | {
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-block';
          }
        | {
            quote: string;
            author?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote-block';
          }
        | {
            type?: ('unordered' | 'ordered') | null;
            items: {
              item: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'list-block';
          }
        | {
            language?: ('typescript' | 'javascript' | 'html-css' | 'json') | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'code-block';
          }
      )[]
    | null;
  centerColumn?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text-block';
          }
        | {
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-block';
          }
        | {
            quote: string;
            author?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote-block';
          }
        | {
            type?: ('unordered' | 'ordered') | null;
            items: {
              item: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'list-block';
          }
        | {
            language?: ('typescript' | 'javascript' | 'html-css' | 'json') | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'code-block';
          }
      )[]
    | null;
  rightColumn?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text-block';
          }
        | {
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-block';
          }
        | {
            quote: string;
            author?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote-block';
          }
        | {
            type?: ('unordered' | 'ordered') | null;
            items: {
              item: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'list-block';
          }
        | {
            language?: ('typescript' | 'javascript' | 'html-css' | 'json') | null;
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'code-block';
          }
      )[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'three-column';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}